ventory:
    plugin: SimpleInventory
    options:
        host_file: "C:/Users/MECOSDE/Desktop/hosts.yaml"
        group_file: "C:/Users/MECOSDE/Desktop/groups.yaml"
nner:
plugin: threaded
options:
    num_workers: 20